export default {
  item: undefined,
  next: undefined,
  prev: undefined,
  pagination: undefined,
  responseType: 'document',
  bind: true,
  scrollContainer: window,
  spinner: false,
  logger: true,
  loadOnScroll: true,
  negativeMargin: 0,
  trigger: false,
  prefill: true,
};
